AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - config/initializers/*
    - config/deploy.rb
    - Guardfile
    - bin/*
    - config/sentry.rb
    - config/deploy/jetruby.rb
    - config/routes.rb
    - app/graph/types/query_root.rb
    - app/graph/types/order_type.rb
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/BlockComments:
  Enabled: false

NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only
